export const APP_BASE = '/traffic-calming'
export const APP_TITLE = 'Traffic Calming Petitioning'
export const API_URL = 'https://dev.franklintn.gov/api/v2/eng/traffic-calming'
// export const API_URL = 'http://cofasv38/api/v2/eng/traffic-calming'
export const NODE_ENV: 'development' | 'test' | 'production' = 'production' 